# this YAML is merged into the chart file and deleted before using helm and deleted afterward in the target directory
kcatImage:
  repository: edenhill/kcat
  tag: "1.7.1"
  pullPolicy: IfNotPresent

busyboxImage:
  repository: busybox
  tag: "1.37.0"
  pullPolicy: IfNotPresent